name: Development

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/.ci.yml
    secrets: inherit
